
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Migracoes usam o owner (BYPASSRLS); o runtime usa DATABASE_URL
    // (painel_app, sujeito ao RLS) em src/lib/db/prisma.ts.
    url: process.env.MIGRATE_DATABASE_URL || env("DATABASE_URL"),
  },
});
